export interface Profile {
  image: string;
  imageAlt?: string;
  name: string;
  role: string;
  quote?: string;
  github?: string;
  linkedin?: string;
  instagram?: string;
  email?: string;
}

export const team: Profile[] = [
  {
    image: '/Images/Team/Vishnu.jpg',
    name: 'Vishnuprasad V Bhat',
    role: 'President',
    quote: 'Embrace the change.',
    linkedin: 'https://in.linkedin.com/in/vishnuprasad-v-bhat-11a32a21a',
    instagram: 'https://instagram.com/vishnuprasadxo?igshid=OGU0MmVlOWVjOQ==',
  },
  {
    image: '/Images/Team/Minal.jpg',
    name: 'Minal Assadi',
    role: 'Vice President ',
    quote: 'Confident and responsible team player, thriving on challenges and working well under pressure. Friendly demeanor, always ready to collaborate effectively.',
    linkedin: 'https://www.linkedin.com/in/minal-assadi-b41510210',
    instagram: 'https://instagram.com/minal.assadi?igshid=OGQ5ZDc2ODk2ZA==',
  },
  {
    image: '/Images/Team/Rifaath.jpg',
    name: 'Rifaath Mohamed Ameen',
    role: 'Branch Captain',
    quote: 'Brown Munde!',
    instagram: 'https://instagram.com/rifaathameen',
    linkedin: 'https://www.linkedin.com/in/rifaathameen/',
    github: 'https://github.com/rifaaath',
  },
  {
    image: '/Images/Team/Akshitha.jpg',
    name: 'Akshitha Shetty',
    role: 'Secretary',
    quote: 'As the Secretary of the branch committee, I am committed to ensuring efficient communication and organization within our engineering community. With a passion for excellence and teamwork, I aim to contribute to the success and cohesion of our branch this year.',
    instagram: 'https://instagram.com/___aakshiii___?utm_source=qr&igshid=OGIxMTE0OTdkZA==',
    linkedin: 'https://www.linkedin.com/in/akshithaashokshetty',
  },
  {
    image: '/Images/Team/Saachi.jpg',
    name: 'Saachi Suvarna',
    role: 'Joint Secretary',
    quote: 'Idk',
    instagram: 'https://instagram.com/saachi_suvarna?igshid=OGQ5ZDc2ODk2ZA==',
    linkedin: 'https://www.linkedin.com/in/saachi-suvarna-6b8a01224',
    github: 'https://github.com/SaachiSuvarna',
  },
  {
    image: '/Images/Team/Brijwin.jpg',
    name: 'Brijwin Balakrishna',
    role: 'Treasurer',
  },
  {
    image: '/Images/Team/Prathwik.jpg',
    name: 'Prathwik Kushal Kumar',
    role: 'Technical Secretary',
    quote: '',
    instagram: 'https://www.instagram.com/prathwik0/',
    github: 'https://github.com/prathwik0',
  },
  {
    image: '/Images/Team/Karthik.jpg',
    name: 'Karthik Shetty',
    role: 'Technical Secretary',
    quote: 'Write whatever you want😂',
    instagram: 'https://instagram.com/karthikshetty555?igshid=OGQ5ZDc2ODk2ZA==',
    linkedin: 'https://www.linkedin.com/in/karthik-shetty-951191248/',
    github: 'https://github.com/KarthikShetty5',
  },
  {
    image: '/Images/Team/Kausthubh.jpg',
    name: 'Kausthubh J Rao',
    role: 'Joint Technical Secretary',
    instagram: 'https://www.instagram.com/_.kaxsthxbh._/',
    github: 'https://github.com/exgene',
  },
  {
    image: '/Images/Team/Chethana.jpeg',
    name: 'Chethana R Kini',
    role: 'Joint Technical Secretary',
    quote: 'We innovate, You succeed.',
    instagram: 'https://instagram.com/chethanarkini?igshid=OGQ5ZDc2ODk2ZA==',
    linkedin: 'https://www.linkedin.com/in/chethana-r-kini',
  },
  {
    image: '/Images/Team/Nandan.png',
    name: 'Nandan R Pai',
    role: 'Web Developer',
    quote: 'Never gonna give you up!',
    instagram: 'https://instagram.com/nandanpi__',
    linkedin: 'https://www.linkedin.com/in/nandanpai09',
    github: 'https://github.com/nandanpi',
  },
  {
    image: '/Images/Team/Pooja.jpeg',
    name: 'Pooja Kotian',
    role: 'Cultural Secretary',
  },
  {
    image: '/Images/Team/Manya.jpg',
    name: 'Manya Hegde',
    role: 'Joint Cultural Secretary',
    quote: 'Sparking cultural passion!',
    instagram: 'https://instagram.com/__manya__hegde__?igshid=YTQwZjQ0NmI0OA==',
    linkedin: 'https://www.linkedin.com/in/manya-hegde-a7216a1aa',
    github: 'https://github.com/manyahegde',
  },
  {
    image: '/Images/Team/Srinidhi.jpg',
    name: 'Srinidhi P',
    role: 'Sports Secretary',
    quote: 'Hang on. It is not over yet.',
    instagram: 'https://instagram.com/srinidhi_palani',
    linkedin: 'https://www.linkedin.com/in/srinidhi-p-875a3427a?trk=contact-info',
    github: 'https://github.com/srinidhipalani',
  },
  {
    image: '/Images/Team/Ninaad.jpg',
    name: 'Ninaad S F Lobo',
    role: 'Joint Sports Secretary',
    quote: 'I am a 10 on the pH scale .',
    instagram: 'https://instagram.com/peaked_in_.highschool?igshid=OGQ5ZDc2ODk2ZA==',
    linkedin: 'https://www.linkedin.com/in/ninaad-lobo-18aa53209',
    github: 'https://github.com/ninnadlobo33',
  },
  {
    image: '/Images/Team/Mesha.jpg',
    name: 'Mesha Shetty B M',
    role: 'Creative Head',
    quote: 'One creative spark at a time.',
    instagram: 'https://www.instagram.com/meshashetty/',
    linkedin: 'https://www.linkedin.com/in/mesha-shetty-518953254',
  },
  {
    image: '/Images/Team/Anoop.jpg',
    name: 'K Anoop Shenoy',
    role: 'Graphic Designer',
    quote: 'I am the graphic designer and if you need any help contact me or DM me anytime .',
    instagram: 'https://instagram.com/_anoop_shenoy?igshid=NzZlODBkYWE4Ng==',
    linkedin: 'https://www.linkedin.com/in/anoop-shenoy-9867b4264',
  },
  {
    image: '/Images/Team/Mallikarjuna.jpg',
    name: 'Mallikarjuna N A',
    role: 'Graphic Designer',
    quote: 'DO NOT STOP WHEN YOU ARE TIRED...STOP WHEN YOU ARE DONE',
    instagram: 'https://instagram.com/mallikarjun_asantapur?igshid=MzMyNGUyNmU2YQ==',
    linkedin: 'https://www.linkedin.com/in/mallikarjuna-n-asantapur-48b578242',
    github: 'https://github.com/mallikarjunaasantapur',
  },
  {
    image: '/Images/Team/Khushi.jpg',
    name: 'Khushi S Bhimani',
    role: 'Media Coordinator',
    quote: 'Capturing ideas to adorn you ',
    instagram: 'https://instagram.com/memory_window_?igshid=OGQ5ZDc2ODk2ZA==',
    linkedin: 'https://www.linkedin.com/in/khushi-bhimani-7bb738249',
    github: 'https://github.com/KhushiSBhimani',
  },
  {
    image: '/Images/Team/Nihal.png',
    name: 'Nihal Mohan Shettigar',
    role: 'Social Media & Publicity Coordinator',
    // Have you ever had a dream, that you -um, you had, your, you-you could, you will do, you-you wants, you could do so, you-you will do so, you-you will do, you could-you, you want, you want him to do you so much you could do anything?
    quote: 'I attend class even after telling everyone i wont attend class! uwu <33333 ',
    instagram: 'https://www.instagram.com/__findingnimo/',
    linkedin: 'https://www.linkedin.com/in/nihal-mohan-8b8984241/',
  },
  {
    image: '/Images/Team/Rahul.jpg',
    name: 'Rahul AR',
    role: 'Social Media & Publicity Asst. Coordinator',
    quote: 'Think, Plan, Excecute',
    instagram: 'https://instagram.com/themonk_who_wants_a_ferrari?utm_source=qr&igshid=MzNlNGNkZWQ4Mg==',
    linkedin: 'https://www.linkedin.com/in/rahul-ar-873876248',
    github: 'https://github.com/rahul-ar-sys',
  },
  {
    image: '/Images/Team/Adril.jpg',
    name: 'Adril Jenice DSA',
    role: 'Magazine Coordinator',
    quote: 'Why fall in love when you can fall asleep',
    instagram: 'https://instagram.com/jenice_adril?igshid=NzZlODBkYWE4Ng==',
    linkedin: 'https://www.linkedin.com/in/adril-jenice-dsa-99267a246',
  },
  {
    image: '/Images/Team/Dhanush.jpg',
    name: 'Dhanush Rajashekar',
    role: 'Magazine Coordinator',
    quote: 'I attend class even after telling everyone i wont attend class',
    instagram: 'https://www.instagram.com/dan.wh0_0sh/',
    linkedin: 'https://www.linkedin.com/in/dhanush-rajshekar-127234246/',
    github: 'https://github.com/Danwhoosh',
  },
  {
    image: '/Images/Team/Cleton.jpg',
    name: 'Cleton Chris Dsouza',
    role: 'MC Committee Head',
    quote: 'Giving up is always an option, but it’s never my choice',
    instagram: 'https://instagram.com/cleton.d?igshid=OGQ5ZDc2ODk2ZA==',
    linkedin: 'https://www.linkedin.com/in/cleton-chris-dsouza-a4ba27231',
    github: 'https://github.com/cleton12',
  },
  {
    image: '/Images/Team/Siddhanth.jpg',
    name: 'M Siddhanth Prabhu',
    role: 'MC Committee Asst.',
    instagram: 'https://instagram.com/msp_636',
  },
  {
    image: '/Images/Team/Harshit.jpg',
    name: 'Harshit Raj',
    role: 'Special Interest Group Head ',
    quote: 'Turning vision into reality!',
    linkedin: 'https://www.linkedin.com/in/iamrajharshit',
  },
  {
    image: '/Images/Team/Zihab.png',
    name: 'Mohammed Zihab',
    role: 'Special Interest Group Asst.',
  },
  {
    image: '/Images/Team/Sinchana.jpg',
    name: 'Sinchana S',
    role: 'Year Representative',
    quote: 'Myself Sinchana S from the department of AIML. I believe I offer a perfect blend of interests in all the fileds may it be technical, cultural or creativity.  ',
    instagram: 'https://instagram.com/sinchu_02?igshid=YTQwZjQ0NmI0OA==',
    linkedin: 'https://www.linkedin.com/in/sinchana-s742700222/',
    github: 'https://github.com/sinchanabhandary',
  },
  {
    image: '/Images/Team/Ameya.jpg',
    name: 'Ameya Guru Kowshik',
    role: '2nd Year CR',
    instagram: 'https://instagram.com/ameya_1074',
    linkedin: 'https://www.linkedin.com/in/ameya-kowshik-b6042a284',
    github: 'https://github.com/ameyakowshik',
  },
];
